drive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userface/', include('userface.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='userface/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

userface/urls.py
from django.urls import path
import re
from . import views
from django.conf.urls import url

app_name = 'userface'
urlpatterns = [
    path('', views.index, name='index'),
]

urlpatterns += [
    path('myvehicles/', views.VehicleListView.as_view(), name='my-vehicles'),
    path('myparking/', views.ParkingSpotListView.as_view(), name='myparking'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
    path('registervehicle/',views.registervehicle, name = 'registervehicle'),
    path('addspot/',views.addspot, name = 'addspot'),
    path('portal',views.portal, name = 'portal')
    #url(r'^mapview/(?P<pk>[0-9]+)$', views.DestinationDetailView.as_view(), name='search_results')
]

userface/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User
# Create your models here.




class Vehicle(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    plateNum = models.CharField(max_length=6, default=' ')

    def __str__(self):
        return self.make + " " + self.model

class ParkingSpot(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.PointField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    upload_image = models.ImageField(upload_to='parkingspot_uploads/', default='parkingspot_uploads/default_image.jpg')
    def __str__(self):
        return self.address


class Destination(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    location = models.PointField()
    city = models.CharField(max_length=50)


class UserLocation(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.PointField()

class UserDetails(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    number = models.CharField(max_length = 20)

userface/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from userface.models import Vehicle
from userface.models import ParkingSpot
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField
    last_name = forms.CharField

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]


class VehicleForm(forms.ModelForm):
    make = forms.CharField(label="Make", required=True)
    model = forms.CharField(label="Model", required=True)
    plateNum = forms.CharField(label="License Plate", required=True)
    #color = forms.CharField(label="Color", required=True)

    helper = FormHelper()
    helper.form_method = 'POST'

    helper.add_input(Submit('Save', 'Save', css_class='btn-primary'))

    class Meta:
        model = Vehicle
        fields = ["make", "model", "plateNum"]

class ParkingSpaceForm(forms.ModelForm):
    address = forms.CharField(label="Address", required=True)
    city = forms.CharField(label="City", required=True)
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('List', 'List', css_class='btn-primary'))
    #helper.form_tag = False
    #helper.form_id = 'addspot'

    class Meta:
        model = ParkingSpot
        fields = ["address", "city", "upload_image"]


userface/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import User, Vehicle, ParkingSpot, Destination, UserDetails
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.gis.geos import Point
from django.contrib.gis.geos import fromstr
from django.contrib.gis.measure import Distance, D
from geopy.distance import distance
from django.contrib.auth.decorators import login_required
# Create your views here.
from .forms import RegisterForm, VehicleForm, ParkingSpaceForm
#from django.contrib.gis.geoip2 import GeoIP2
from django.contrib.gis.geos import fromstr
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
from django.views.generic import DetailView


def words_to_point(q):
    geolocator = Nominatim(user_agent="driveways")
    location = geolocator.geocode(q)
    point = Point(location.latitude, location.longitude)
    return point



def index(request):

    return render(request, 'userface/index.html')


def portal(request):

    return render(request, 'userface/adminportal.html')

def search(request):

    if request.method == "GET":
        resultss = request.GET.get('results', False)
        if not resultss:
            resultss = ""

        try:

            destination = words_to_point(resultss)

        except (GeocoderTimedOut, AttributeError) as e:
            request.session['spot'] = []
            return render(request, 'userface/search.html', {'resultss': resultss})

        spot_distance = request.GET.get('distance', False )
        try:
            val = int(spot_distance)
        except ValueError:
            print("That's not an int!")
            spot_distance = 3
        request.session['spot'] = "unknown"
        if request.user.is_authenticated:
            c_user = request.user
            dest = c_user.destination_set.create(
                address=resultss, location=destination)
            dest.save()
            request.session['spot'] = []
            near_spots = ParkingSpot.objects.filter(
                location__distance_lt=(destination, Distance(km=spot_distance)))
            for spot in near_spots:
                if len(spot.address) > 0:
                    try :

                        details = UserDetails.objects.get(owner = spot.owner)
                        number = details.number

                    except UserDetails.DoesNotExist:
                        number = ""

                    request.session['spot'].append(
                        {"address": spot.address,
                         "owner": spot.owner.first_name + " " + spot.owner.last_name,
                         "image_path": spot.upload_image.url,
                         "lon": spot.location.y,
                         "lat": spot.location.x,
                         "number": number})
    return render(request, 'userface/search.html', {'resultss': resultss, 'dest': dest})


def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()

        return redirect("/userface")
    else:
        form = RegisterForm()

    return render(response, "registration/register.html", {"form": form})


class VehicleListView(LoginRequiredMixin, generic.ListView):
    model = Vehicle
    #context_object_name = 'vehicles'
    template_name = 'userface/user_vehicle_list.html'

    def get_queryset(self):
        return Vehicle.objects.filter(user=self.request.user)[:5]

class ParkingSpotListView(LoginRequiredMixin, generic.ListView):
    model = ParkingSpot
    #context_object_name = 'vehicles'
    template_name = 'userface/parking_spot_list.html'

    def get_queryset(self):
        return ParkingSpot.objects.filter(owner=self.request.user)[:]

def registervehicle(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST)
        if form.is_valid():
            vehicle = form.save(commit=False)
            vehicle.make = form.cleaned_data.get('make')
            vehicle.model = form.cleaned_data.get('model')
            vehicle.plateNum = form.cleaned_data.get('plateNum')
            vehicle.user = request.user
            vehicle.save()
        return redirect("/userface/myvehicles")
    else:
        form = VehicleForm()

    return render(request, "userface/register_vehicle.html", {"form": form})


def addspot(request):
    if request.method == 'POST':
        form = ParkingSpaceForm(request.POST)
        if form.is_valid():
            parkingspot = form.save(commit=False)
            parkingspot.address = form.cleaned_data.get('address')
            parkingspot.city = form.cleaned_data.get('city')
            fullAddress = form.cleaned_data.get(
                'address') + " " + form.cleaned_data.get('city')
            parkingspot.location = words_to_point(fullAddress)
            parkingspot.owner = request.user
            parkingspot.save()
        return redirect("/userface/myparking")
    else:
        form = ParkingSpaceForm()

    return render(request, "userface/addspot.html", {"form": form})

userface/templates/userface/addspot.html
{% extends "userface/parking_spot_list.html" %}

{% block title %}  <h1 class="h2">Register Parking</h1>  {% endblock title %}

  {% block action %}
   <a href="{% url 'userface:myparking'%}" class="btn btn-sm btn-outline-secondary">Your Parking Spots</a>
  {% endblock action %}



{% block content %}
{% load crispy_forms_tags %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.address|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.city|as_crispy_field }}
      </div>
      <div class="form-group">
        {{ form.upload_image|as_crispy_field }}
      </div>
    </div>
    <button type = "submit" class="btn btn-sm btn-outline-secondary">Submit</button>
  </form>
{% endblock %}

userface/templates/userface/adminportal.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>
     <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/portal.css' %}">
  </head>

  <body>

    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'userface:search'%}">Home</a>
      <ul class="navbar-nav px-3">

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"  id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Options</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item"  href="{% url 'userface:myparking'%}">
                <span data-feather="home"></span>
                  My Parking
                </a>
              <a class="dropdown-item" href="{% url 'userface:my-vehicles'%}">
                  <span data-feather="truck"></span>
                  My Vehicles
                </a>

              <a class="dropdown-item" href="{% url 'userface:myparking'%}">
                <span data-feather="book-open"></span>
                  My History
              </a>

               <a class="dropdown-item" href="{% url 'logout'%}?next=/userface">
                <span data-feather="log-out"></span>
                  Logout
              </a>

            </div>

          </li>

      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              {% block active %}
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userface:my-vehicles'%}">
                  <span data-feather="truck"></span>
                  My Vehicles
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userface:myparking'%}">
                  <span data-feather="home"></span>
                  My parking
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Payment Info
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="book-open"></span>
                  My history
                </a>
              </li>
              {% endblock active %}
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            </h6>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
  {% block title %}  <h1 class="h2">Dashboard</h1>  {% endblock title %}
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                  {% block action %}

                  {% endblock action %}
              </div>
            </div>
          </div>

          {% block content %}
            {% if user.is_authenticated %}
            <h3 class="h3"> Welcome to your portal, {{ user.get_username }}! </h3>
            {% else %}
            {% endif %}
            {% endblock content %}

        </main>
      </div>
    </div>



    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>

  </body>


userface/templates/userface/cover.html
{% load static %}

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'login'%}?next={% url 'userface:search'%}">Login</a>
            <a class="nav-link active" href="{% url 'userface:register'%}?next={{request.path}}">Register</a>
          </nav>
        </div>
      </header>
      {%  block search %}
      <main role="main" class="inner cover">
        <h1 class="cover-heading">Welcome to Driveways!</h1>

      </main>
      {% endblock search %}
       <div class="flex" style="margin: 10px;padding: 10px; border-top:solid white; border-width: medium;"></div>

      <footer class="mastfoot mt-auto">
        <div class="inner">
        </div>
      </footer>
    </div>


  </body>


userface/templates/userface/index.html
{% extends "userface/cover.html" %}



{% block content %}
{% if user.is_authenticated %}



{% else %}

{% endif %}
{% endblock %}

userface/templates/userface/parking_spot_list.html
{% extends "userface/adminportal.html" %}
 <title>My Parking</title>
  {% block active %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userface:portal'%}">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userface:my-vehicles'%}">
                  <span data-feather="truck"></span>
                  My Vehicles
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'userface:myparking'%}">
                  <span data-feather="home"></span>
                  My parking
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Payment Info
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="book-open"></span>
                  My reviews
                </a>
              </li>
              {% endblock active %}





{% block title %}  <h1 class="h2">Parking List</h1>  {% endblock title %}

  {% block action %}
   <a href="{% url 'userface:addspot'%}" class="btn btn-sm btn-outline-secondary">Register Parking</a>
  {% endblock action %}
{% block content %}

<style>
ul {
  list-style-type: none;
}
</style>

    {% if parkingspot_list %}

    <ul style="margin:10px;">
<div class="list-group">

      {% for parking in parkingspot_list %}


          <li class="list-group-item"> {{ parking.address }} {{parking.city}}</li>

      {% endfor %}
      </div>
    </ul>

    {% else %}
      <p>You have no parking spots</p>
    {% endif %}
{% endblock %}


userface/templates/userface/register_vehicle.html

{% extends "userface/user_vehicle_list.html" %}




{% block title %}  <h1 class="h2">Register Vehicle</h1>  {% endblock title %}

  {% block action %}
   <a href="{% url 'userface:my-vehicles'%}" class="btn btn-sm btn-outline-secondary">Your Vehicles</a>
  {% endblock action %}


{% block content %}
{% load crispy_forms_tags %}
  <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.make|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.model|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.plateNum|as_crispy_field }}
      </div>
    </div>
    <button type = "submit" class="btn btn-sm btn-outline-secondary">Submit</button>
  </form>
{% endblock %}

userface/templates/userface/search.html
{% extends "userface/search_base.html" %}


{% if user.is_authenticated %}

    {% load crispy_forms_tags %}

    {% block body %}
    <div class="flex" style="margin: 5px;padding: 5px">
    <div>
    <div class="flex flex-wrap" style="margin:20px">
      <form method="get">
        <label for="results">Enter Destination Address: </label>
        <div class="flex flex-wrap">
        <div>
        <input id="results" class="form-control" type="text" name="results" value="{{ search_results }}">
           <label for="distance">Enter Max distance from location (km): </label>
         <input id="distance" class="form-control" type="text" name="distance" value="{{ search_distance }}">
        </div>
        <div style="margin-left: 10px">
            <br/>
        <button type="submit" class="btn btn-success" >
          Submit
        </button>
        </div>
        </div>
      </form>
    </div>



    {% if resultss and request.session.spot and request.session.spot.0 %}
    <div style="margin: 10px">
        <h1 class="h5" > {{resultss}} </h1>
        <h3 class="h6"> Parking Spots next to Destination: </h3>
        {% comment %} <li> {{}} </li> {% endcomment %}
        <div class="flex flex-wrap">
        {% for spot in request.session.spot %}
          {% if spot.address %}
            <div class="card" style="width: 12rem; margin: 15px;">
                <a href = "{% url 'userface:myparking'%}"> <img src="{{ spot.image_path }}" class="card-img-top" alt="No-image"></a>
              <div class="card-body">
                <p class="card-text" >Address: {{spot.address}}
                </p>
                <p class="card-text">Owner: {{spot.owner}}</p>
                  <p class="card-text">Phone Number: {{spot.number}}</p>
              </div>
            </div>
          {% endif %}

        {% endfor %}
        </div>
    </div>



{% load leaflet_tags %}

{% leaflet_css %}

{% leaflet_js %}



<div>
    {% leaflet_map "main" callback="map_init" %}
</div>


<script type="text/javascript">

    function map_init(map, options) {

        // get point lat and lon

        var lat = "{{ dest.location.x }}";

        var lon = "{{ dest.location.y }}";

        // zoom to point & add it to map
        map.setView([lat, lon], 12);
        L.marker([lat, lon], {title: "Destination"}).addTo(map);
       "{% for spot in request.session.spot %}"
          L.marker(["{{spot.lat}}", "{{spot.lon}}"], {title: "Parking Spot"}).addTo(map);
        "{% endfor %}"

    }

</script>

    {% else %}
   
    {%if resultss and not request.session.spot%}
      <h4 class="h4" style="margin:10px;">No Parking Spots to {{resultss}}</h4>
    {% else %}

    {% endif %}
    {% endif %}
    </div>
    </div>
    {% endblock body %}

{% else %}
{% endif %}

userface/templates/userface/search_base.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Home Search</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
      {% load static %}
    <link rel="stylesheet" href="{% static 'css/starter-template.css' %}">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Driveways Search</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'userface:portal'%}">Admin Portal</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout'%}?next=/userface">Logout</a>
          </li>

        </ul>

      </div>
    </nav>

    {% block body %}
    <main role="main" class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </main><!-- /.container -->
    {% endblock body %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

userface/templates/userface/user_vehicle_list.html
{% extends "userface/adminportal.html" %}


 <title>My Parking</title>
  {% block active %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userface:portal'%}">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'userface:my-vehicles'%}">
                  <span data-feather="truck"></span>
                  My Vehicles
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userface:myparking'%}">
                  <span data-feather="home"></span>
                  My parking
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Payment Info
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="book-open"></span>
                  My reviews
                </a>
              </li>
              {% endblock active %}




{% block title %}  <h1 class="h2">Vehicle List</h1>  {% endblock title %}

  {% block action %}
   <a href="{% url 'userface:registervehicle'%}" class="btn btn-sm btn-outline-secondary">Register Vehicle</a>
  {% endblock action %}
{% block content %}

<style>
ul {
  list-style-type: none;
}
</style>

    {% if vehicle_list %}
    
    <ul style="margin:10px;">
<div class="list-group">

      {% for vehicle in vehicle_list %}
      
          
          <li class="list-group-item"> {{ vehicle.make }} {{vehicle.model}}</li>
        
      {% endfor %}
      </div>
    </ul>

    {% else %}
      <p>You have no vehicles</p>
    {% endif %}
{% endblock %}
